services:
#    analytics.example:
#        class: AnalyticsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  Donfelice\AnalyticsBundle\EventListener\MyAdminUIMenuListener:
    public: true
    tags:
      - { name: kernel.event_subscriber }
